#docker-composeのバージョン
version: '3'
services:
  db:
    image: postgres
    ports:
      - '5432:5432' # ホストからゲストへポートフォワード
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY
    command: /bin/sh -c "rm -f /WashletSearchApp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' && echo $$GOOGLE_MAPS_API_KEY"
    tty: true
    stdin_open: true
    depends_on:
      - db # DB側のコンテナが出来上がってからbackendを実行する
    ports:
      - "3000:3000" # ホストからゲストへポートフォワード
    volumes:
      - .:/WashletSearchApp # ソースコード変更したらDocker側も即反映されるように
volumes:
  postgresql-data:
    driver: local