
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: googlemap_development

test:
  <<: *default
  database: googlemap_test

production:
  <<: *default
  database: googlemap_production
  username: googlemap
  password: <%= ENV['googlemap_DATABASE_PASSWORD'] %>
